// for(let i = 1; i <= 10; i++){
//     document.write(i , ": this is loop <br>")
// }
// for(let i = 10; i >= 1; i--){
//     document.write(i , ": this is loop <br>")
// }
// let a = +prompt("Enter the num for table")
// for (let b=1; b<=10; b++){
//     document.write(a , "X" , b , "=" , b*a , "<br>")
// }

// let a = 1
// while(a<=10){
//     document.write(a , " This is while loop <br>")
//     a++
// }
// let a = 10
// while(a>=1){
//     document.write(a , " This is while loop <br>")
//     a--
// }
// let a = 0
// let sum = 0

// while(a<=10){

// }